#CREATE DATABASE
DROP DATABASE IF EXISTS CarSystem;
CREATE DATABASE CarSystem;

#SELECT THE DATABASE 
USE CarSystem;

#TABLE CAR_INSTANCES
CREATE TABLE CAR_TYPE(
CatId INT NOT NULL, 
TYPE VARCHAR(100) NOT NULL,
CAT_DESC VARCHAR(250) NOT NULL,
PRIMARY KEY(CatId)
) Engine= InnoDB;

#TABLE CARS
CREATE TABLE CAR(
CarId VARCHAR(10) NOT NULL,
BRAND VARCHAR(100) NOT NULL, 
MODEL VARCHAR(100) NOT NULL, 
CatId INT NOT NULL,
PRICE NUMERIC(5,0) NOT NULL,
AVAILABILITY CHAR(3) NOT NULL,
PRIMARY KEY(CarId)
) Engine=InnoDB;

#TABLE CUSTOMERS 
CREATE TABLE CUSTOMERS(
CustomerId varchar(10) NOT NULL, 
FIRSTNAME varchar(100) NOT NULL, 
LASTNAME varchar(100) NOT NULL, 
MOBILE varchar(100) NOT NULL, 
STATE varchar(50) NOT NULL, 
COUNTRY varchar(50) NOT NULL, 
EMAIL varchar(100) DEFAULT NULL,
PRIMARY KEY(CustomerId)
)Engine= InnoDB;

#TABLE RESERVATIONS
CREATE TABLE RESERVATION(
ReservationId varchar(4) NOT NULL, 
CustomerId varchar(10) NOT NULL, 
CarId VARCHAR(10) NOT NULL,
CatId INT NOT NULL, 
AMOUNT NUMERIC(7,0) NOT NULL, 
PICKUPDATE DATETIME NOT NULL, 
RETURNDATE DATETIME NOT NULL,
PRIMARY KEY(ReservationId)
) Engine=InnoDB;


ALTER TABLE CAR
ADD CONSTRAINT fkCar_Type
FOREIGN KEY(CatId) REFERENCES CAR_TYPE(CatId);

ALTER TABLE RESERVATION
ADD CONSTRAINT fkCarId
FOREIGN KEY (CarId) REFERENCES CAR(CarId),
ADD CONSTRAINT fkCustomerId
FOREIGN KEY (CustomerId) REFERENCES CUSTOMERS(CustomerId),
ADD CONSTRAINT fkCatId
FOREIGN KEY (CatId) REFERENCES CAR_TYPE(CatId);




