#CREATE DATABASE
DROP DATABASE IF EXISTS CarSystem;
CREATE DATABASE CarSystem;

#SELECT THE DATABASE 
USE CarSystem;

#TABLE CAR_INSTANCES
CREATE TABLE CAR_TYPE(
ID_CATEGORY INT NOT NULL, 
CAR_TYPE VARCHAR(100) NOT NULL,
CAT_DESC VARCHAR(250) NOT NULL,
PRIMARY KEY(ID_CATEGORY)
) Engine= InnoDB;

#TABLE CARS
CREATE TABLE CAR(
CAR_ID VARCHAR(10) NOT NULL,
BRAND VARCHAR(100) NOT NULL, 
MODEL VARCHAR(100) NOT NULL, 
ID_CATEGORY INT NOT NULL,
PRICE NUMERIC(5,0) NOT NULL,
AVAILABILITY CHAR(3) NOT NULL,
PRIMARY KEY(CAR_ID)
) Engine=InnoDB;

#TABLE CUSTOMERS 
CREATE TABLE CUSTOMERS(
CUSTOMER_ID varchar(10) NOT NULL, 
FIRSTNAME varchar(100) NOT NULL, 
LASTNAME varchar(100) NOT NULL, 
MOBILE varchar(100) NOT NULL, 
STATE varchar(50) NOT NULL, 
COUNTRY varchar(50) NOT NULL, 
EMAIL varchar(100) DEFAULT NULL,
PRIMARY KEY(CUSTOMER_ID)
)Engine= InnoDB;

#TABLE RESERVATIONS
CREATE TABLE RESERVATION(
RESERVATION_ID varchar(4) NOT NULL, 
CUSTOMER_ID varchar(10) NOT NULL, 
CAR_ID VARCHAR(10) NOT NULL,
ID_CATEGORY INT NOT NULL, 
AMOUNT NUMERIC(7,0) NOT NULL, 
PICKUPDATE DATETIME NOT NULL, 
RETURNDATE DATETIME NOT NULL,
PRIMARY KEY(RESERVATION_ID)
) Engine=InnoDB;


ALTER TABLE CAR
ADD CONSTRAINT fkCar_Type
FOREIGN KEY(ID_CATEGORY) REFERENCES CAR_TYPE(ID_CATEGORY);

ALTER TABLE RESERVATION
ADD CONSTRAINT fkCAR_ID
FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID),
ADD CONSTRAINT fkCUSTOMER_ID
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
ADD CONSTRAINT fkCAT_ID
FOREIGN KEY (ID_CATEGORY) REFERENCES CAR_TYPE(ID_CATEGORY);




