#CREATE DATABASE
DROP DATABASE IF EXISTS CarSystem;
CREATE DATABASE CarSystem;

#SELECT THE DATABASE 
USE CarSystem;

#TABLE CAR_INSTANCES
CREATE TABLE CAR_TYPE(
ID_CATEGORY INT(10) NOT NULL, 
CAR_TYPE VARCHAR(100) NOT NULL,
CAT_DESC VARCHAR(250) NOT NULL,
PRIMARY KEY(ID_CATEGORY)
);

#TABLE CARS
CREATE TABLE CAR(
CAR_ID VARCHAR(10) NOT NULL,
BRAND VARCHAR(100) NOT NULL, 
MODEL VARCHAR(100) NOT NULL, 
ID_CATEGORY INT(10) NOT NULL,
PRICE NUMERIC(5,0) NOT NULL,
AVAILABILITY CHAR(3) NOT NULL,
PRIMARY KEY(CAR_ID)
);

#TABLE CUSTOMERS 
CREATE TABLE CUSTOMERS(
CUSTOMER_ID varchar(10) NOT NULL, 
FIRSTNAME varchar(100) NOT NULL, 
LASTNAME varchar(100) NOT NULL, 
MOBILE varchar(100) NOT NULL, 
STATE varchar(50) NOT NULL, 
COUNTRY varchar(50) NOT NULL, 
EMAIL varchar(100) DEFAULT NULL,
PRIMARY KEY(CUSTOMER_ID)
);

#TABLE RESERVATIONS
CREATE TABLE RESERVATION(
RESERVATION_ID varchar(4) NOT NULL, 
CUSTOMER_ID varchar(10) NOT NULL, 
CAR_ID VARCHAR(10) NOT NULL,
ID_CATEGORY INT(10) NOT NULL, 
AMOUNT double NOT NULL, 
PICKUPDATE date NOT NULL, 
RETURNDATE date NOT NULL,
PRIMARY KEY(RESERVATION_ID)
);


ALTER TABLE CAR
ADD CONSTRAINT fkCar_Type
FOREIGN KEY(ID_CATEGORY) REFERENCES CAR_TYPE(ID_CATEGORY);






